feat: support import cache size by env
wechaty/wechaty-puppet pull request #137
Opened 2021-07-08 12:57 UTC by su-chang

2021-07-08 13:08 UTC, windmemory requested changes

2021-07-08 13:08 UTC, windmemory commented on src/config.ts
> +const ROOM_MEMBER_CACHE_SIZE = process.env['ROOM_MEMBER_CACHE_SIZE'] || '2000'
It would be better to not change the default value of the current cache.

2021-07-09 03:01 UTC, windmemory approved these changes
Looks good to me, approved!

2021-07-13 08:10 UTC, huan requested changes
Thanks for the improvements!

Please use a formated env var name with `WECHATY_PUPPET_` namespace:

  CONTACT_CACHE_SIZE -> WECHATY_PUPPET_LRU_CACHE_SIZE_CONTACT
  FRIENDSHIP_CACHE_SIZE -> WECHATY_PUPPET_LRU_CACHE_SIZE_FRIENDSHIP
  MESSAGE_CACHE_SIZE -> WECHATY_PUPPET_LRU_CACHE_SIZE_MESSAGE
  ROOM_CACHE_SIZE -> WECHATY_PUPPET_LRU_CACHE_SIZE_ROOM
  ROOM_INVITATION_CACHE_SIZE -> WECHATY_PUPPET_LRU_CACHE_SIZE_ROOM_INVITATION
  ROOM_MEMBER_CACHE_SIZE -> WECHATY_PUPPET_LRU_CACHE_SIZE_ROOM_MEMBER

2021-07-13 15:14 UTC, windmemory approved these changes

2021-07-15 12:23 UTC, huan approved these changes
LGTM

Thank you very much for the improvements!

2021-07-15 12:23 UTC, merged